name: learn-github-actions
on: [push]
jobs:
  count-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node ./.github/scripts/main.js
