name: count-actions
on: [push]
jobs:
  count-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node ./.github/scripts/main.js
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "ankh04"
          git add README.md
          git commit -m "update README.md"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
